version: '3'

services:
    flask_test_1:
        build:
            context: ./flask_1
            dockerfile: Dockerfile
        ports:
            - 8501:8501
    flask_test_2:
        build:
            context: ./flask_2
            dockerfile: Dockerfile
        ports:
            - 3000:3000
    flask_test:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 5000:5000
